CREATE TABLE Progress
(
	ProgressID INTEGER PRIMARY KEY,
	StudentID INTEGER NOT NULL,
	ClassroomID INTEGER NOT NULL,
	Score INTEGER NOT NULL,
	FOREIGN KEY (StudentID) REFERENCES Students (StudentID),
	FOREIGN KEY (ClassroomID) REFERENCES Class_rooms (ClassroomID)
);