CREATE TABLE Students 
(
	StudentID INTEGER PRIMARY KEY,
	First_name VARCHAR(255) NOT NULL,
	Last_name VARCHAR(255) NOT NULL,
	Country VARCHAR(255) NOT NULL,
	Language VARCHAR(255) NULL,
	Date_birth DATE null
);